const foodData = [
  {
    id: 1,
    name: "Onion Samosa",
    price: 15,
    image: "/pictures/sam1.png",
    description: "Crispy, golden-fried onion samosa.",
  },
  {
    id: 2,
    name: "Aloo Samosa",
    price: 20,
    image: "/pictures/sam2.png",
    description: "Crispy, golden-fried samosa with a spiced potato filling.",
  },
  {
    id: 3,
    name: "Chicken Samosa",
    price: 25,
    image: "/pictures/sam3.png",
    description: "Crispy, golden-fried samosa stuffed with spicy chicken.",
  },
  {
    id: 4,
    name: "Chicken Biryani",
    price: 125,
    image: "/pictures/bir1.png",
    description: "Delicious spiced rice cooked with tender chicken.",
  },
  {
    id: 5,
    name: "Egg Biryani",
    price: 99,
    image: "/pictures/bir2.png",
    description: "Fragrant rice cooked with aromatic spices and boiled eggs.",
  },
  {
    id: 6,
    name: "Paneer Biryani",
    price: 140,
    image: "/pictures/bir3.png",
    description: "Flavorful biryani with marinated paneer and aromatic spices.",
  },
  {
    id: 7,
    name: "Chicken Burger",
    price: 99,
    image: "/pictures/bur1.png",
    description: "Juicy chicken patty with fresh lettuce, cheese, and sauce.",
  },
  {
    id: 8,
    name: "Veg Burger",
    price: 79,
    image: "/pictures/bur2.png",
    description: "Crispy veggie patty with fresh lettuce, cheese, and sauce.",
  },
  {
    id: 9,
    name: "Cheese Burger",
    price: 99,
    image: "/pictures/bur3.png",
    description: "Juicy patty topped with melted cheese and fresh lettuce.",
  },
  {
    id: 10,
    name: "Chapathi",
    price: 50,
    image: "/pictures/chapathi.png",
    description: "Soft, warm flatbread made with whole wheat.",
  },
  {
    id: 11,
    name: "Chicken Puff",
    price: 40,
    image: "/pictures/chickenpuff.png",
    description: "Flaky pastry filled with spiced, tender chicken.",
  },
  {
    id: 12,
    name: "Coffee",
    price: 20,
    image: "/pictures/cof2.png",
    description: "Smooth, bold coffee with a rich, robust flavor.",
  },
  {
    id: 13,
    name: "Sprite",
    price: 20,
    image: "/pictures/cool3.png",
    description: "Refreshing, chilled beverage to beat the heat.",
  },
  {
    id: 14,
    name: "Pepsi",
    price: 20,
    image: "/pictures/pepsi.png",
    description: "Refreshing, chilled beverage with a bold cola taste.",
  },
  {
    id: 15,
    name: "Mazaa",
    price: 20,
    image: "/pictures/Mazaa.png",
    description: "Delicious mango-flavored drink, perfect for summer.",
  },
  {
    id: 16,
    name: "Chocolate Ice Cream",
    price: 40,
    image: "/pictures/Icecream1.png",
    description: "A velvety smooth, chocolatey delight.",
  },
  {
    id: 17,
    name: "Butterscotch Ice Cream",
    price: 40,
    image: "/pictures/pngwing.com.png",
    description: "Creamy, caramelized delight with rich butterscotch flavor.",
  },
  {
    id: 18,
    name: "Vanilla Ice Cream",
    price: 40,
    image: "/pictures/vannila1.png",
    description: "Classic vanilla ice cream with a rich and creamy texture.",
  },
  {
    id: 19,
    name: "Veg Puff",
    price: 15,
    image: "/pictures/vegpuff.png",
    description: "A crispy, flaky pastry filled with a spiced vegetable mix.",
  },
  {
    id: 20,
    name: "Egg Puff",
    price: 20,
    image: "/pictures/eggpuff.png",
    description: "A crispy, flaky pastry filled with a spiced egg filling.",
  },
  {
    id: 21,
    name: "Chai Biscuit",
    price: 20,
    image: "/pictures/Tea-Biscuit.png",
    description: "Classic tea-time biscuit for a perfect chai pairing.",
  },
  {
    id: 22,
    name: "Idly",
    price: 35,
    image: "/pictures/idli.png",
    description: "Soft, fluffy steamed rice cakes served with chutney and sambar.",
  },
  {
    id: 23,
    name: "Dosa",
    price: 40,
    image: "/pictures/dosa.png",
    description: "Crispy, golden-brown crepe, best with chutney and sambar.",
  },
  {
    id: 24,
    name: "Puri",
    price: 40,
    image: "/pictures/puri.png",
    description: "Deep-fried, puffy bread, best with potato curry.",
  },
  {
    id: 25,
    name: "Paratha and Curry",
    price: 60,
    image: "/pictures/paratha.png",
    description: "Flaky flatbread paired with flavorful curries.",
  },
  {
    id: 26,
    name: "Veg Meal",
    price: 80,
    image: "/pictures/meals.png",
    description: "A wholesome platter of rice, curry, and sides.",
  },
  {
    id: 27,
    name: "Non-Veg Meal",
    price: 110,
    image: "/pictures/nonveg.png",
    description: "Rice, meats, curries, and sides for a hearty meal.",
  },
  {
    id: 28,
    name: "French Fries",
    price: 70,
    image: "/pictures/fries.png",
    description: "Crispy, golden fries, perfect as a snack or side dish.",
  },
  {
    id: 29,
    name: "Veg Momos",
    price: 60,
    image: "/pictures/vmomo.png",
    description: "Steamed or fried dumplings filled with vegetables.",
  },
  {
    id: 30,
    name: "Chicken Momos",
    price: 80,
    image: "/pictures/cmomo.png",
    description: "Steamed or fried dumplings with flavorful chicken.",
  },
  {
    id: 31,
    name: "Chicken Noodles",
    price: 90,
    image: "/pictures/chickennoodles.png",
    description: "A mix of noodles, chicken, and savory spices.",
  },
  {
    id: 32,
    name: "Egg Noodles",
    price: 80,
    image: "/pictures/eggnoodles.png",
    description: "Stir-fried noodles with egg, vegetables, and spices.",
  },
  {
    id: 33,
    name: "Veg Noodles",
    price: 70,
    image: "/pictures/vegnoodles.png",
    description: "Stir-fried noodles loaded with fresh vegetables.",
  },
  {
    id: 34,
    name: "Chicken Manchuria",
    price: 100,
    image: "/pictures/chickenmanch.png",
    description: "Crispy chicken tossed in spicy Manchurian sauce.",
  },
  {
    id: 35,
    name: "Veg Manchuria",
    price: 80,
    image: "/pictures/vegmanch.png",
    description: "Crispy vegetable balls in Manchurian sauce.",
  },
  {
    id: 36,
    name: "Fried Rice",
    price: 80,
    image: "/pictures/friedrice.png",
    description: "Stir-fried rice with vegetables and spices.",
  },
];

export default foodData;
